services:
  pg:
    container_name: flaskDb
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  api:
    container_name: flaskApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
    ports:
      - 5000:5000
    depends_on:
      - pg
    environment:
      FLASK_ENV: development
    command: bash -c 'while !</dev/tcp/pg/5432; do sleep 1; done; flask db upgrade && flask run -h 0.0.0.0'
