"""create tables

Revision ID: 8455b2a9f7f1
Revises: 
Create Date: 2022-07-08 13:27:50.441486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8455b2a9f7f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('dataNascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idPessoa'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('transacao',
    sa.Column('idTransacao', sa.Integer(), nullable=False),
    sa.Column('idConta', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dataTransacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idTransacao')
    )
    op.create_table('conta',
    sa.Column('idConta', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('limiteSaqueDiario', sa.Float(), nullable=False),
    sa.Column('flagAtivo', sa.Boolean(), nullable=False),
    sa.Column('tipoConta', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.Date(), nullable=False),
    sa.Column('idPessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.idPessoa'], ),
    sa.PrimaryKeyConstraint('idConta'),
    sa.UniqueConstraint('idPessoa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    op.drop_table('transacao')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
