"""create relation 1:n

Revision ID: 920576461669
Revises: 8455b2a9f7f1
Create Date: 2022-07-08 14:21:55.685690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920576461669'
down_revision = '8455b2a9f7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacao', 'idConta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'transacao', 'conta', ['idConta'], ['idConta'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacao', type_='foreignkey')
    op.alter_column('transacao', 'idConta',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
